authentication/urls.py
# pylint: disable=C0103
"""urls module.
"""
from django.urls import path

from .views.account_view import AccountView
from .views.sign_up_view import SignUpView
from .views.sign_in_view import SignInView
from .views.sign_out_view import SignOutView

app_name = 'authentication'

urlpatterns = [
    path('sign_up/', SignUpView.as_view(), name='sign_up'),
    path('sign_in/', SignInView.as_view(), name='sign_in'),
    path('sign_out/', SignOutView.as_view(), name='sign_out'),
    path('account/', AccountView.as_view(), name='account'),
]

supersub/urls.py
"""Urls module
"""
from django.urls import path


from .views.favorites_view import FavoritesView
from .views.index_view import IndexView
from .views.legal_mentions_view import LegalMentionsView
from .views.product_detail_view import ProductDetailView
from .views.register_favorite_view import RegisterFavoriteView
from .views.register_rating_view import RegisterRatingView
from .views.result_view import ResultView

app_name = 'supersub'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path(
        'product_detail/<int:id_prod>', ProductDetailView.as_view(),
        name='product_detail'
    ),
    path('favorites/', FavoritesView.as_view(), name='favorites'),
    path('results/', ResultView.as_view(), name='results'),
    path(
        'register_favorite/<int:id_prod>', RegisterFavoriteView.as_view(),
        name='register_favorite'
    ),
    path(
        'register_rating/<int:id_prod>', RegisterRatingView.as_view(),
        name='register_rating'
    ),
    path('legal_mentions/', LegalMentionsView.as_view(), name='legal_mentions')
]

authentication/models.py
"""CustomUser model module.
"""
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _

from authentication.management.custom_user_manager import CustomUserManager


class CustomUser(AbstractUser):
    """CustomUser model class. It sa an abstarct of django user class which
    provides all user authenticaiton, login, etc. methods. Implemented in
    order to have email as identifier instead of username provided by default
    by django framework.
    """
    username = None
    email = models.EmailField(_('email address'), max_length=250, unique=True)
    first_name = models.TextField(_('first name'), max_length=100, null=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name']

    objects = CustomUserManager()

    def __str__(self):
        return self.email

authentication/forms/sign_in_form.py
"""Sign in form module.
"""
from django.contrib.auth.forms import AuthenticationForm
from django import forms


class SignInForm(AuthenticationForm):
    """Sign in form class.
    """
    username = forms.CharField(
        label="Email",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'autofocus': True,
                'id': 'id_signin_email_input'
            }
        )
    )
    password = forms.CharField(
        label="Mot de passe",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'id': 'id_signin_password_input'
            }
        )
    )

authentication/forms/sign_up_form.py
"""Sign up form module.
"""
from django import forms
from django.contrib.auth.forms import UserCreationForm

from authentication.models import CustomUser


class SignUpForm(UserCreationForm):
    """Sign up form class.
    """
    first_name = forms.CharField(
        label="Prénom",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'autofocus': True,
                'id': 'id_first_name_input'
            }
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'id': 'id_email_input'
            }
        )
    )
    password1 = forms.CharField(
        label="Mot de passe",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'id': 'id_pwd1_input'
            }
        )
    )
    password2 = forms.CharField(
        label="Confirmer le mot de passe",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'id': 'id_pwd2_input'
            }
        )
    )

    class Meta(UserCreationForm):
        """Meta model gives CustomUser "params" to Signupform lcass.
        """
        model = CustomUser
        fields = ['first_name', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'autofocus': False})

authentication/views/account_view.py
"""Accout view module.
"""
from django.shortcuts import render, redirect

from supersub.views.custom_view import CustomView


class AccountView(CustomView):
    """Accout view class.
    """
    def __init__(self):
        super().__init__()
        self._data['redirect'] = 'authentication:sign_in'
        self._data['render'] = 'authentication/account.html'

    def get(self, request):
        """Account view method on client get request. View is dipslayed if the
        user is authenticated.
        """
        if not request.user.is_authenticated:
            return redirect(self._data['redirect'])
        self._data['ctxt']['user'] = request.user
        return render(request, self._data['render'], self._data['ctxt'])

authentication/views/sign_in_view.py
# pylint: disable=W0212
"""Sign in view module.
"""
from django.shortcuts import render, redirect

from authentication.forms.sign_in_form import SignInForm
from authentication.management.authentication_manager import (
    AuthenticationManager
)
from supersub.views.custom_view import CustomView


class SignInView(CustomView, AuthenticationManager):
    """Sign in view class.
    """
    def __init__(self):
        super().__init__()
        self._data['redirect'] = 'supersub:index'
        self._data['render'] = 'authentication/sign_in.html'

    def get(self, request):
        """Sign in view method on client get request.
        """
        form = SignInForm()
        self._data['ctxt']['form'] = form
        return render(request, self._data['render'], self._data['ctxt'])

    def post(self, request):
        """Sign in view method on client post request. If the user is present
        and its autheticaion is successfull, the user is redirected to the
        index page. If any of those criteria is not met, the same page is
        rendered to the user.
        """
        self._logout(request)
        form = SignInForm(data=request.POST)
        if form.is_valid():
            user = self._authenticate(form.cleaned_data)
            if user is not None:
                self._login(request, user)
                return redirect(self._data['redirect'])
        self._data['ctxt']['form'] = form
        return render(request, self._data['render'], self._data['ctxt'])

authentication/views/sign_out_view.py
# pylint: disable=W0212
"""Sign out view module.
"""
from django.shortcuts import redirect

from authentication.management.authentication_manager import (
    AuthenticationManager
)
from supersub.views.custom_view import CustomView


class SignOutView(CustomView, AuthenticationManager):
    """Sign out view class.
    """
    def __init__(self):
        super().__init__()
        self._data['redirect'] = 'supersub:index'

    def get(self, request):
        """Sign out method on client get request. After logging the user
        out, the user is redirected to the index page.
        """
        self._logout(request)
        return redirect(self._data['redirect'])

authentication/views/sign_up_view.py
# pylint: disable=W0212
"""Sign up view module.
"""
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authentication.forms.sign_up_form import SignUpForm
from authentication.management.authentication_manager import (
    AuthenticationManager
)
from supersub.views.custom_view import CustomView


class SignUpView(CustomView, AuthenticationManager):
    """Sign up view class.
    """
    def __init__(self):
        super().__init__()
        self._data['redirect'] = 'authentication:sign_in'
        self._data['render'] = 'authentication/sign_up.html'

    def get(self, request):
        """Sign up view method on client get request.
        """
        form = SignUpForm()
        self._data['ctxt']['form'] = form
        return render(request, self._data['render'], self._data['ctxt'])

    def post(self, request):
        """Sign up view method on client post request. If the user is not
        present in DB and the form provided info are ok, the user is
        redirected to the sign in page. If any of those criteria is not met,
        the same page is rendered to the user.
        """
        form = SignUpForm(request.POST)
        if form.is_valid():
            self._create_user(form.cleaned_data)
            return HttpResponseRedirect(reverse(self._data['redirect']))
        self._data['ctxt']['form'] = form
        return render(request, self._data['render'], self._data['ctxt'])

authentication/templates/authentication/account.html
{% extends 'supersub/base.html' %}

{% block content %}
    <!-- Masthead-->
    <header class="searchhead" id="searched">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center"> 
                <div class="col-lg-8 align-self-center mb-2">
                    <h2 class="text-white-75 mb-4"> {{ user.first_name}} </h2>
                </div>
            </div>
        </div>
    </header>
    <!-- User email display section-->
    <div class="page-section bg-white" id="services">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 text-center">
                    <h4 class="m-4 text-dark"> {{ user.email}}</h4>
                </div>
                <div class="col-8 col-lg-10 pl-2 pt-5">
                    <a href="{% url 'authentication:sign_in'%}" id="go_to_create_account" class="text-dark text-center">
                        <p class="pt-4">Pas votre compte? Se connecter avec votre compte.</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/sign_in.html
{% extends 'supersub/base.html' %}

{% block content %}
    <!-- Masthead-->
    <header class="searchhead" id="searched">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-8 align-self-center mb-2">
                    <h2 class="text-white-75 mb-4">Connection</h2>
                </div>
            </div>
        </div>
    </header>
    <!-- Form section-->
    <div class="page-section bg-white" id="services">
        <div class="container">
            <div class="row justify-content-center">
                <form action="{% url 'authentication:sign_in'%}" method="post">
                    {% csrf_token %}
                    <div class="form-group align-content-center">
                        <div class="row justify-content-center">
                            <div class="col-8 col-lg-10 pl-2 text-dark w-100">
                                {% for field in form %}
                                    <p>
                                        {{ field.label_tag }}<br>
                                        {{ field }}
                                        {% for error in field.errors %}
                                            <p class="text-primary"> {{ error }}</p>
                                        {% endfor %}
                                    </p>
                                {% endfor %}
                            </div>
                            <div class="col-8 col-lg-10 pl-2 pt-5">
                                <button type="submit" id="id_sign_in_button" class=" btn btn-primary mb-4">Se connecter</button>
                                <a href="{% url 'authentication:sign_up'%}" id="go_to_create_account" class="text-dark text-center">
                                    <p class="pt-4">Pas de compte? Créer un compte</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/sign_up.html
{% extends 'supersub/base.html' %}

{% block content %}
    <!-- Masthead-->
    <header class="searchhead" id="searched">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-8 align-self-center mb-2">
                    <h2 class="text-white-75 mb-4"> Créer un compte </h2>
                </div>
            </div>
        </div>
    </header>
    <!-- Form section-->
    <div class="page-section bg-white" id="services">
        <div class="container">
            <div class="row justify-content-center">
                <form action="{% url 'authentication:sign_up' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group align-content-center">
                        <div class="row justify-content-center">
                            <div class="col-8 col-lg-10 pl-2 text-dark w-100">
                                {% for field in form %}
                                <p>
                                    {{ field.label_tag }}<br>
                                    {{ field }}
                                    {% for error in field.errors %}
                                    <p class="text-primary"> {{ error }}</p>
                                    {% endfor %}
                                </p>
                                {% endfor %}
                            </div>
                            <div class="col-8 col-lg-10 pl-2 pt-5">
                                <button type="submit" id="id_sign_up_button" class=" btn btn-primary mb-4">Créer le compte</button>
                                <a href="{% url 'authentication:sign_in'%}" id="create_account_go_to_login" class="text-dark text-center">
                                    <p class="pt-4">Déja un compte? Connectez-vous</p>
                                </a>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}