authentication/urls.py
# pylint: disable=C0103
"""urls module.
"""
from django.urls import path

from .views.account_view import AccountView
from .views.sign_up_view import SignUpView
from .views.sign_in_view import SignInView
from .views.sign_out_view import SignOutView

app_name = 'authentication'

urlpatterns = [
    path('sign_up/', SignUpView.as_view(), name='sign_up'),
    path('sign_in/', SignInView.as_view(), name='sign_in'),
    path('sign_out/', SignOutView.as_view(), name='sign_out'),
    path('account/', AccountView.as_view(), name='account'),
]

supersub/urls.py
"""Urls module
"""
from django.urls import path


from .views.favorites_view import FavoritesView
from .views.index_view import IndexView
from .views.legal_mentions_view import LegalMentionsView
from .views.product_detail_view import ProductDetailView
from .views.register_favorite_view import RegisterFavoriteView
from .views.register_rating_view import RegisterRatingView
from .views.result_view import ResultView

app_name = 'supersub'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path(
        'product_detail/<int:id_prod>', ProductDetailView.as_view(),
        name='product_detail'
    ),
    path('favorites/', FavoritesView.as_view(), name='favorites'),
    path('results/', ResultView.as_view(), name='results'),
    path(
        'register_favorite/<int:id_prod>', RegisterFavoriteView.as_view(),
        name='register_favorite'
    ),
    path(
        'register_rating/<int:id_prod>', RegisterRatingView.as_view(),
        name='register_rating'
    ),
    path('legal_mentions/', LegalMentionsView.as_view(), name='legal_mentions')
]

supersub/models/category.py
"""Category module model
"""
from django.db import models


class Category(models.Model):
    """Category class model
    """
    id_origin = models.CharField(max_length=200)
    name = models.CharField(max_length=200, unique=True)
    url = models.URLField(max_length=200, null=True)

supersub/models/favorites.py
# pylint: disable=E1101
"""Favorites module model
"""
from django.db import models

from authentication.models import CustomUser
from supersub.models.product import Product


class Favorites(models.Model):
    """Favorites class model. Composed of Custom User and Product classes
    foreign keys
    """
    custom_user = models.ForeignKey(CustomUser, models.CASCADE)
    product = models.ForeignKey(Product, models.CASCADE)

    def __str__(self):
        return self.custom_user.email

supersub/models/product.py
# pylint: disable=E1101
"""Products module model
"""
from django.db import models
from django.db.models import Avg

from authentication.models import CustomUser
from supersub.models.category import Category


class Product(models.Model):
    """Products class model. Category attribute is a foreign from Catgeory
    class.
    """
    id_origin = models.CharField(max_length=200)
    name = models.CharField(max_length=200, unique=True)
    nutriscore_grade = models.CharField(max_length=8)
    fat = models.DecimalField(max_digits=8, decimal_places=3)
    saturated_fat = models.DecimalField(max_digits=8, decimal_places=3)
    sugar = models.DecimalField(max_digits=8, decimal_places=3)
    salt = models.DecimalField(max_digits=8, decimal_places=3)
    image = models.URLField(max_length=200)
    url = models.URLField(max_length=200)
    categories = models.TextField()
    category = models.ForeignKey(Category, models.CASCADE)
    relation_custom_user = models.ManyToManyField(
        CustomUser, through='Favorites'
    )

    def product_rating(self):
        """ product rating method. Method returns the average ratings for
        the product. It uses its relation with Ratings model.
        """
        avg_rating = self.ratings_set.all().aggregate(Avg('rate'))
        avg_rating = avg_rating['rate__avg']
        if avg_rating:
            avg_rating = int(avg_rating)
        return avg_rating

    def product_count(self):
        """ Product count method. Method returns the number of rating for
        the product. It uses its relation with Ratings model.
        """
        product_count = Product.objects.filter(
            ratings__product_id=self.id
        ).count()
        return product_count

supersub/models/ratings.py
# pylint: disable=E1101
"""Ratings module model
"""
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from authentication.models import CustomUser
from supersub.models.product import Product


class Ratings(models.Model):
    """Ratings class model. Composed of Custom User and Product classes
    foreign keys.
    """
    custom_user = models.ForeignKey(CustomUser, models.CASCADE)
    product = models.ForeignKey(Product, models.CASCADE)
    rate = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )

    def __str__(self):
        return self.product.name

supersub/forms/main_search_form.py
"""Main search form module
"""
from django import forms


class MainSearchForm(forms.Form):
    """Main search form class. Used for searching product substitute
    """
    product = forms.CharField(
        label=None,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'autofocus': True,
                'id': 'id_main_form'
            }
        )
    )

supersub/forms/navbar_search_form.py
"""Navigation bar search form module
"""
from django import forms


class NavbarSearchForm(forms.Form):
    """Navigation bar search form class. Used for searching product substitute
    with the navbar form
    """
    product = forms.CharField(
        label=None,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mybox'
            }
        )
    )

supersub/forms/ratings_form.py
"""Ratings form module
"""
from django import forms


class RatingsForm(forms.Form):
    """Ratings form class. Used for rating products.
    """
    choices_list = [
        (None, ""),
        (1, "Très mauvais (une étoile)"),
        (2, "Mauvais (deux étoiles)"),
        (3, "Moyen (trois étoiles)"),
        (4, "Bon (quatre étoiles)"),
        (5, "Très bon (cinq étoiles)")
    ]
    ratings = forms.IntegerField(
        label="Note le produit:",
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'id': 'rating_form_attr'
            },
            choices=choices_list,
        )
    )

supersub/views/custom_view.py
""" Custom view module
"""
from django.views import View

from supersub.forms.main_search_form import MainSearchForm
from supersub.forms.navbar_search_form import NavbarSearchForm
from supersub.management.app.supersub_manager import SupersubManager


class CustomView(View, SupersubManager):
    """Custom view class
    """
    def __init__(self):
        super().__init__()
        self._data = self._get_data()
        self._data['ctxt']['main_form'] = MainSearchForm()
        self._data['ctxt']['navbar_form'] = NavbarSearchForm()
        self._data['ctxt']['searched_prod'] = ''
        self._data['ctxt']['prod'] = ''
        self._data['ctxt']['page_obj'] = ''
        self._data['ctxt']['user'] = ''
        self._data['ctxt']['form'] = ''
        self._data['render'] = ''
        self._data['redirect'] = ''

supersub/views/favorites_view.py
# pylint: disable=W0212
""" Favorites view module.
"""
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from supersub.views.custom_view import CustomView


class FavoritesView(CustomView):
    """Favorites view class.
    """
    def __init__(self):
        super().__init__()
        self._data['render'] = 'supersub/favorites.html'
        self._data['redirect'] = 'supersub:index'

    def get(self, request):
        """ Favorite view method on client get request. The response renders
        all the favorites from the authenticated user. In case the user has
        not register any favorite or he'll be redirected ot the index page.
        The same will occur if an un-auntehnticated user try ot see its
        favorites.
        """
        if request.user.is_authenticated:
            favorites = list(self._filter_favorites(request.user.id))
            if favorites:
                self._data['ctxt']['page_obj'] = (
                    self._get_page(request, favorites)
                )
                return render(
                    request, self._data['render'], self._data['ctxt'])
            messages.add_message(
                request,
                messages.WARNING,
                "Vous n'avez enregistré aucun favoris jusqu'à présent"
            )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                "Connectez-vous pour consulter vos favoris!"
            )
        return HttpResponseRedirect(reverse(self._data['redirect']))

supersub/views/index_view.py
# pylint: disable=W0212
"""Index view module.
"""
from django.shortcuts import render

from supersub.views.custom_view import CustomView


class IndexView(CustomView):
    """Index view class.
    """
    def __init__(self):
        super().__init__()
        self._data['render'] = 'supersub/index.html'

    def get(self, request):
        """Index/home page view method on client get request.
        """
        self._delete_session_vars(request)
        return render(request, self._data['render'], self._data['ctxt'])

supersub/views/legal_mentions_view.py
# pylint: disable=W0212
"""Legal mentions view module.
"""
from django.shortcuts import render

from supersub.views.custom_view import CustomView


class LegalMentionsView(CustomView):
    """Legal mentions view class.
    """
    def __init__(self):
        super().__init__()
        self._data['render'] = 'supersub/legal_mentions.html'

    def get(self, request):
        """Legal mention page view method on client get request.
        """
        return render(request, self._data['render'], self._data['ctxt'])

supersub/views/product_detail_view.py
# pylint: disable=W0212
"""Product detail view module.
"""
from django.shortcuts import render

from supersub.views.custom_view import CustomView
from supersub.forms.ratings_form import RatingsForm


class ProductDetailView(CustomView):
    """Product detail view class.
    """
    def __init__(self):
        super().__init__()
        self._data['render'] = 'supersub/product_detail.html'

    def get(self, request, id_prod):
        """Product detail page view method on client get request.
        """
        self._data['ctxt']['prod'] = self._get_product(id_prod)
        self._data['ctxt']['ratings_form'] = RatingsForm()
        self._data['ctxt']['user'] = request.user
        self._data['ctxt']['user_product_rating'] = (
            self._get_user_product_rating(id_prod, request.user)
        )
        return render(request, self._data['render'], self._data['ctxt'])

supersub/views/register_favorite_view.py
# pylint: disable=W0212
"""Register favorite view module.
"""
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse

from supersub.views.custom_view import CustomView


class RegisterFavoriteView(CustomView):
    """Register favorite view class.
    """
    def __init__(self):
        super().__init__()
        self._data['redirect'] = 'supersub:product_detail'

    def get(self, request, id_prod):
        """Register favorite method on client get request. On the attempt
        of registering the favorite, the user is redirected to the product
        detail page. If the favorite is already a user favorites', he'll get
        a waring message. If the favorite is not already a user favorite, a
        success message is displayed.
        """
        if self._get_favorite(id_prod, request.user.id):
            messages.add_message(
                request, messages.WARNING, "Produit déja enregistré"
            )
        else:
            self._save_favorite(id_prod, request.user.id)
            messages.add_message(
                request, messages.SUCCESS, "Produit enregistré!"
            )
        return HttpResponseRedirect(
            reverse(self._data['redirect'], args=[id_prod])
        )

supersub/views/register_rating_view.py
# pylint: disable=W0212
"""Register rating view module.
"""
from django.http import HttpResponseRedirect
from django.urls import reverse

from supersub.forms.ratings_form import RatingsForm
from supersub.views.custom_view import CustomView


class RegisterRatingView(CustomView):
    """Register rating view class.
    """
    def __init__(self):
        super().__init__()
        self._data['redirect'] = 'supersub:product_detail'

    def post(self, request, id_prod):
        """Register rating method on client post request. On the attempt
        of registering its rating, the user is redirected to the product
        detail page.
        """
        form = RatingsForm(request.POST)
        if form.is_valid():
            form_value = form.cleaned_data['ratings']
            self._save_rating(id_prod, request.user.id, form_value)
        return HttpResponseRedirect(
            reverse(self._data['redirect'], args=[id_prod])
        )

supersub/views/result_view.py
# pylint: disable=W0212, E1101
"""Result view module.
"""
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from supersub.models.product import Product
from supersub.views.custom_view import CustomView


class ResultView(CustomView):
    """Result view class.
    """
    def __init__(self):
        super().__init__()
        self._data['render'] = 'supersub/results.html'
        self._data['redirect'] = 'supersub:index'

    def get(self, request):
        """Result page view method on client get request. Renders the selected
        product(after its capture on a previous post request)
        and its potential substitutes
        """
        prod_id, prods_ids = self._get_session_vars(request)
        self._data['ctxt']['searched_prod'] = self._get_product(prod_id)
        self._data['ctxt']["page_obj"] = (
            self._get_page_from_session_vars(request, prods_ids))
        self._data['ctxt']['user'] = request.user
        return render(request, self._data['render'], self._data['ctxt'])

    def post(self, request):
        """Result page view method on client post request. Renders the
        selected product and its potential substitutes. In case that the
        product is not recognized by the system, a warning message is
        displayed and the user is redirected to the index page. If no product
        is typed into the form and submitted an error messages is displayed
        and the user is redirected to the index page.
        """
        form = self._get_form(request)
        if form.is_valid():
            match_prods = (
                Product.objects.filter(
                    name__contains=form.cleaned_data['product']
                )[:1]
            )
            if match_prods:
                self._data['ctxt']['searched_prod'] = match_prods[0]
                self._data['ctxt']["page_obj"] = (
                    self._get_page_from_form(request, match_prods[0])
                )
                self._add_vars_to_session(request, match_prods[0])
                self._data['ctxt']['user'] = request.user
                return render(
                    request, self._data['render'], self._data['ctxt']
                )
            messages.add_message(
                request, messages.WARNING,
                "Ce produit n'a pas été reconnu ou n'existe pas."
            )
        else:
            messages.add_message(
                request, messages.ERROR, "Saisissez un produit"
            )
        return HttpResponseRedirect(reverse(self._data['redirect']))

supersub/templates/supersub/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>P8 - Pur-beurre</title>
        
        <!-- Favicon-->
        <!-- <link rel="icon" type="image/x-icon" href="assets/img/logo_pur_beurre-favicon.ico" /> -->
        <link rel="icon" type="image/x-icon" href="{% static 'supersub/assets/img/logo_pur_beurre-favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'supersub/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'supersub/css/my_styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <img src="{% static 'supersub/assets/img/logo_pur_beurre.png' %}" id="navbar_bur_beurre_logo" width="40" height="30" alt="Pur beurre logo">
                <a class="navbar-brand js-scroll-trigger pl-2" href="{% url 'supersub:index'%}" id="navbar_pur_beurre_texte">Pur Beurre</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0 align-items-center">
                        <li>
                            <form id="navbar_search_form" action="{% url 'supersub:results'%}" method="post" class="d-flex pl-4 pr-4" novalidate>
                                {% csrf_token %}
                                {% for field in navbar_form %}
                                    {{ field }}
                                    {% for error in field.errors %}
                                        <p class="text-primary"> {{ error }}</p>
                                    {% endfor %}
                                {% endfor %}
                            </form>
                        </li>
                        <li class="nav-item nav-link js-scroll-trigger navbar-brand">
                            <a href="{% url 'authentication:account'%}">
                                <i class="fas fa-user" id="user_icon"></i>
                            </a>
                        </li>
                        <li class="nav-item nav-link js-scroll-trigger navbar-brand">
                            <a href="{% url 'supersub:favorites' %}">
                                <i class="fas fa-carrot" id="carrot_icon" data-fa-transform="rotate-315"></i>
                            </a>
                        </li>
                        <li class="nav-item nav-link js-scroll-trigger navbar-brand">
                            <a href="{% url 'authentication:sign_out'%}">
                                <i class="fas fa-sign-out-alt" id="logout_icon"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Block content-->
        <div>
            {% block content %}{% endblock %}
        </div>
        <!-- Footer-->
        <footer class="bg-dark py-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <div class="row">
                            <div class="col-sm-6 align-self-center text-muted"><a href="{% url 'supersub:legal_mentions'%}" class="footer-text">Mention légales</a></div>
                            <div class="col-sm-6 align-self-center text-muted"><a href="{% url 'supersub:index'%}#contact" class="footer-text">Contact</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'supersub/js/scripts.js' %}"></script>
    </body>
</html>

supersub/templates/supersub/favorites.html
{% extends 'supersub/base.html' %}

{% block content %}

    {% load static %}
    
    <!-- Masthead-->
    <header class="searchhead" id="searched">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center"> 
                <div class="col-lg-8 align-self-center mb-2">
                    <h2 class="text-white-75 mb-4">Mes favoris</h2>
                </div>
            </div>
        </div>
    </header>
    <!-- Services-->
        <section class="page-section bg-white" id="services">
            <div class="container">
                <div class="row">
                    {% for favorite in page_obj %}
                        <div class="col-lg-4 col-sm-6 text-center">
                            <div class="m-4 results-image">
                                <a href="{% url 'supersub:product_detail' id_prod=favorite.product.id %}" class="ele_dark_href">
                                    <img style="max-height: 80px;" src=" {{ favorite.product.image }} " alt="" />
                                    <p class="h5 m-1"> {{ favorite.product.name }} </p>
                                </a>
                                <div class="nutriscore-circle">
                                    <i class="fas fa-circle"></i>
                                </div>
                                <div class="nutriscore-letter text-uppercase">
                                    <p>{{ favorite.product.nutriscore_grade }}</p>
                                </div>
            
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% include 'supersub/pagination.html' %}
            </div>
        </section>
{% endblock %}

supersub/templates/supersub/index.html
{% extends 'supersub/base.html' %}

{% block content %}
    <!-- Masthead-->
    {% load static %}
    <header class="masthead" id="search">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-10 align-self-end">
                    <h1 class="text-uppercase text-white font-weight-bold">Du Gras, oui mais de qualité</h1>
                    <hr class="divider my-4"/>
                </div>
                <div class="col-lg-8 align-self-center mb-2">
                    <h2 class="text-white-75 font-weight-light">Trouvez un produit de substitution pour ceux que vous
                        consommez tous les jours!</h2>
                </div>
                <div class="col-10 col-md-8 col-lg-5 align-self-start">
                    {% if messages %}
                        {% for message in messages %}
                        <div class="row">
                            <div class="col">
                                <h6 {% if message.tags %} class="{{ message.tags }} mb-3" {% endif %}>
                                    {{ message }}
                                </h6>
                            </div>
                        </div>
                        {% endfor %}
                    {% endif %}
                    <form id="index_main_search_form" action="{% url 'supersub:results'%}" method="post" novalidate>
                        {% csrf_token %}
                        <div class="form-group align-content-center">
                        <div class="row justify-content-center">
                            <div class="col-8 col-lg-10 pl-2 w-100">
                                {% for field in main_form %}
                                    <p>
                                        {{ field }}
                                        {% for error in field.errors %}
                                            <p class="text-primary"> {{ error }}</p>
                                        {% endfor %}
                                    </p>
                                {% endfor %}
                            </div>
                            <div class="col-8 col-lg-10 pl-2 ">
                                <button type="submit" id="index_search_button" class=" btn btn-primary mb-4">Chercher</button>
                            </div>
                        </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>
    <!-- About Colette & Remy-->
    <section class="page-section bg-primary" id="about">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-white mt-0">Colette et Rémy</h2>
                    <hr class="divider light my-4" />
                    <p class="text-white mb-4">Pur Beurre est l'initiative de deux amoureux de la gastronomie française,
                        Colette Tatou et Rémy, que vous avez déjà
                        certainement rencontrés dans notre excellent restaurant Ratatouille</p>
                    <div class="row">
                        <div class="col-sm-6 align-self-center">
                            <img src="{% static 'supersub/assets/img/colette.png' %}" width="150" alt="colette">
                        </div>
                        <div class="col-sm-6 align-self-center">
                            <img src="{% static 'supersub/assets/img/remy.png' %}" width="150" alt="remy">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact-->
    <section class="page-section bg-white" id="contact">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-dark mt-0">Contactez-nous!</h2>
                    <hr class="divider light my-4" />
                    <p class="text-dark-75 mb-4">N'hésitez pas à nous contacter par téléphone ou email!</p>
                    <div class="row">
                        <div class="col-sm-6 align-self-center text-secondary">
                            <i class="fas fa-phone fa-rotate-90"></i>
                            <p class="text-dark-75 text-center mt-2">00.00.00.00.00</p>
                        </div>
                        <div class="col-sm-6 align-self-center text-secondary">
                            <i class="far fa-envelope"></i>
                            <p class="text-dark-75 mt-2">mail@mail.com</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

supersub/templates/supersub/pagination.html
<div class="row align-items-end text-center">
    <div class="col">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}#favorite_section" class="ele_dark_href">&laquo;</a>
        {% endif %}

        <span class="current text-dark">
            Page {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}#favorite_section" class="ele_dark_href">&raquo;</a>
        {% endif %}
    </div>
</div>

supersub/templates/supersub/results.html
{% extends 'supersub/base.html' %}

{% block content %}
    {% if searched_prod.name %}
        {% load static %}
        <!-- Masthead-->
        <header class="searchhead lg" id="searchhead" style="background-image:url('{{searched_prod.image}}');">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center"> 
                    <div class="col-lg-8 align-self-center mb-2">
                        <a href="{% url 'supersub:product_detail' id_prod=searched_prod.id %}" class="product-text">
                            <h2 id="result_searched_product" class="mb-4 zl"> {{ searched_prod.name }} </h2>
                        </a>
                    </div>
                </div>
            </div>
        </header>
        <!-- Services-->
        <div class="page-section bg-white" id="favorite_section">
            <div class="container">
                <h4 class="text-dark text-center text-secondary-50 mb-4"> Vous pouvez remplacer ce produit par:  </h4>
                <hr class="divider my-4" />
                <div class="row">
                    {% for product in page_obj %}
                        <div class="col-lg-4 col-sm-6 text-center">
                            <div class="m-4 results-image">
                                <a href="{% url 'supersub:product_detail' id_prod=product.id %}" class="ele_dark_href" id="subsitute_product">
                                    <img style="max-height: 80px;"  src=" {{ product.image }} " alt="" />
                                    <p class="h5 m-1"> {{ product.name }} </p>
                                </a>
                                <div class="nutriscore-circle">
                                    <i class="fas fa-circle"></i>
                                </div>
                                <div class="nutriscore-letter text-uppercase">
                                    <p>{{ product.nutriscore_grade }}</p>
                                </div>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'supersub:register_favorite' id_prod=product.id%}" class="ele_dark_href">
                                        <p class="mb-0">
                                            <span>
                                                <i class="fas fa-save"></i>
                                            </span>
                                            Sauvegarder
                                        </p>
                                    </a>
                                    {% if message %}
                                        <p class=text-primary> {{mesage}}</p>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% include 'supersub/pagination.html' %}
            </div>
        </div>
    {% endif %}
{% endblock %}